### ISSUE TITLE
[Sugestão] Valores Especiais como Expressões Regulares

### ISSUE THREAD

**Issue by henry701** [HenGuirelli/RestTest#1]
As notações `${ANY}` e `${NUMBER}` cobrem a maioria dos casos de uso aplicáveis, mas pensando em generalização, há outra forma de abordar a solução.

Um mecanismo plugável de Expressões Regulares que considerasse, por exemplo:

`CUSTOMER_NAME|${/.+?/}|CUSTOMER_NUMBER|${\d+?}`

Se tornando a regex:

`CUSTOMER_NAME\|.+?\|CUSTOMER_NUMBER\|\d+?`

E então sendo aplicada na validação.

O uso de Regexes também permite extrair valores do corpo e utilizar ao longo do resto das expressões de validação. O exemplo mais claro que vem a mente seria valores de data ISO, por exemplo a data atual trafegada no JSON como uma string `2020-07-12T09:10:05.123-03:00`.

Isso daria margem para, no futuro, estar inserindo uma notação para interpretar determinados valores como datas, e operadores que permitissem comparar com relações menor-maior e efetuar operações aritméticas básicas. Cobriria, então, a esmagadora maioria de testes REST que hoje são implementadas em código de teste unitário.

Para manter a legibilidade nos casos mais simples, `@{ANY}` e `@{NUMBER}` passariam a ser basicamente _aliases_ para `${.+?}` e `${\d+?}`, utilizando `@` invés de `$` para evitar conflitos.

O que acha da ideia?

**Comment by HenGuirelli** [comment]
O suporte para expressões regulares na validação já existe mas tem uma sintaxe especifica: `${Regex: <regex>}` então a notação `${ANY}` poderia ser substituída por `${Regex: .+?}` e `CUSTOMER_NAME|${/.+?/}|CUSTOMER_NUMBER|${\d+?}` vira `${Regex: CUSTOMER_NAME\\|.+?CUSTOMER_NUMBER\\|\\d+?}`  (precisa de duas barras). Falha minha que esqueci de colocar no readme rs.

Vale ressaltar que não é possível (ainda) combinar o gerenciador de dependência com Regex, por exemplo, pegar o retorno da primeira requisição filtrar via regex por capturing groups e usar apenas o grupo capturado.

Para o futuro adicionar expressões logicas e condicionais seria uma boa adição realmente.
